apiVersion: apps/v1
kind: Deployment
metadata:
  name: Demerit
  labels:
    app: Demerit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Demerit
  template:
    metadata:
      labels:
        app: Demerit
    spec:
      containers:
        - name: Demerit
          image: username/Demerit:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5